### ISSUE TITLE
Is this working with StyleX 0.7.5?

### ISSUE THREAD

**Issue by BMCwebdev** [Dwlad90/stylex-swc-plugin#13]
Just checking in to see if this will work with the latest StyleX version. Thank you!

**Comment by Dwlad90** [comment]
Yes, this plugin can be used as an alternative to the current latest version of the StyleX babel plugin. However, it is worth noting that this project is at an early stage of development and under certain conditions there may be bugs or incorrect behavior. If you suddenly find something like this, please open issues and I will try to fix them in the next version of the plugin.

Thank you for your interest in this project 🙂
