### ISSUE TITLE
[BUG] Needs to provide vendor prefixes properly

### ISSUE THREAD

**Issue by VersorVerbi** [Dwlad90/stylex-swc-plugin#146]
### Describe the bug

Vendor prefixes are not properly supported at the moment. The necessary preceding `-` is omitted from the property name in output, so `WebkitBoxOrient` becomes `webkit-box-orient` instead of the appropriate `-webkit-box-orient`.

### Error stack

No error message is output. The desired CSS does not work as intended.

### Compiler version

@stylexswc/rs-compiler 0.4.4

### Bundler plugin(s) version

@stylexswc/nextjs-plugin 0.4.4

### To Reproduce

1. Add the following CSS to an object that can contain a lot of text (I used `styles.p` in `Card.tsx` in your `nextjs-app-dir-stylex` repo).
    ```ts
    {
        WebkitBoxOrient: "vertical",
        WebkitLineClamp: 2,
        display: "-webkit-box",
        overflow: "hidden"
    }
    ```
2. Make sure there's an instance of that style that has >2 lines of text

If you look at the output CSS, you see `webkit-box-orient` and `webkit-line-clamp`, but without the proper `-` prefix, they don't function correctly.

I'm not using `0.5.0` because I'm still using Next 14 and not able to upgrade past it at the moment.

### Additional information

- [X] I have checked with the latest version

**Comment by Dwlad90** [comment]
Hi @VersorVerbi,
Thanks for finding the bug.

PR #147  with the fix was merged and is available in version `0.5.1-rc.1`.

I also downgrade the minimal version of `react` to `14` for `@stylexswc/nextjs-plugin`, since the plugin supports this version, so you can update `@stylexswc/nextjs-plugin` to the latest version(`0.5.*`).
