### ISSUE TITLE
Whitespace around slashes in urls

### ISSUE THREAD

**Issue by martinbooth** [Dwlad90/stylex-swc-plugin#41]
It looks like styles such as the following cause problems:
```
backgroundImage: "url('/test/test.jpg')"
```
There's unexpected whitespace being inserted around the slashes in the style:
```
background-image: url( / test / test.jpg)
```

I tested it in the demo app so it doesn't seem like it's something I have misconfigured, and I also tested in the stylex playground (which is really just a stackblitz nextjs/stylex app) and the url is not rewritten (the correct behavior):
```
background-image:url('/test/test.jpg')
```
So hopefully I've narrowed down the bug to the correct component and sharing here is helpful

**Comment by Dwlad90** [comment]
Hi, @martinbooth

Thank you so much for finding the bugs.

The [PR](#42) with the fix has been merged. The fixed URL handling will be available in the next release soon.

**Comment by Dwlad90** [comment]
Hi @martinbooth, 

Version `0.3.0`, which includes a fix for this issue, was published on npm
