### ISSUE TITLE
Keyframe properties after first are ignored.

### ISSUE THREAD

**Issue by BjornHMS** [Dwlad90/stylex-swc-plugin#66]
Only the first property defined in a keyframe are used.

```ts
const fadeInAndRotate = stylex.keyframes({
  '0%': { opacity: 0, transform: 'rotateX(-90deg)' },
  '60%': { opacity: 1, transform: 'rotateX(20deg)' },
  '100%': { opacity: 1, transform: 'rotateX(0deg)' },
});
```
compiles to
```ts
{
  '0%': { opacity: 0 },
  '60%': { opacity: 1 },
  '100%': { opacity: 1 },
}
```
and 
```ts
const test = stylex.keyframes({
  '0%': { backgroundColor: '#fff', width: 100, height: 0 },
  '50%': { translate: -100 },
  '100%': { opacity: 0.5, width: 150, height: 200 },
});
```
compiles to
```ts
{
  '0%': { backgroundColor: '#fff' },
  '50%': { translate: -100 },
  '100%': { opacity: 0.5 },
}

**Comment by BjornHMS** [comment]
In the mean time I can use multiple keyFrame animations at  the same time.
Only the first property defined in a keyframe are used.

```ts
const fadeIn = stylex.keyframes({
  '0%': { opacity: 0 },
  '100%': { opacity: 1 },
});
const blackToWhite = stylex.keyframes({
  '0%': { backgroundColor: '#000' },
  '100%': { backgroundColor: '#fff' },
});

const animation = stylex.create({
  fadeIn: {
    animationName: `${fadeIn}, ${blackToWhite}`,
    animationDuration: '2s, 1s',
  },
});
```

However I'm not sure this is a problem with the swc-plugin as I don't know if styleX supports multiple properties in it's keyframes. All googled examples always only showed animations using a single property.

**Comment by Dwlad90** [comment]
Hi @BjornHMS ,

Your provided  examples is a valid `StyleX` code, the problem is in the SWC plugin. Thanks for finding the bug.

The fix is ​​in the [PR](https://github.com/Dwlad90/stylex-swc-plugin/pull/68) and will be available in the next release

**Comment by BjornHMS** [comment]
My pleasure @Dwlad90

Thank you for your continued support.
