### ISSUE TITLE
Passing `null` to stylex.props crashes with `Illegal Argument: Known(Null)`

### ISSUE THREAD

**Issue by VersorVerbi** [Dwlad90/stylex-swc-plugin#92]
### Describe the bug

Using the Babel compiler, you can pass conditional styles with ternaries, like `isTrue ? styles.something : null`, but with the SWC compiler, this causes a crash and you have to use `isTrue && styles.something`. Ideally, either would function the same way.

### Error stack

The error is being thrown from `crates/stylex-shared/src/shared/utils/core/stylex_merge.rs:80`

### OS

Windows

### Compiler version

rs-compiler-win32-x64-msvc 0.4.1

### Bundler plugin(s) version

0.4.1

### To Reproduce

I was able to reproduce in [Dwlad90/nextjs-app-dir-stylex](https://github.com/Dwlad90/nextjs-app-dir-stylex) by adding `Math.random() > 1 ? styles.p : null` to a `stylex.props` call in `Card.tsx`

### Additional information

- [X] I have checked with the latest version

**Comment by Dwlad90** [comment]
Hi @VersorVerbi,
Thanks for finding the problem.

#96 with the fix was merged and will be available in the next `0.4.2-rc.2` version soon.
